// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	FuncaRes
	FuncaRep
	FuncbRes
	FuncbRep
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type FuncaRes struct {
	ID   int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *FuncaRes) Reset()                    { *m = FuncaRes{} }
func (m *FuncaRes) String() string            { return proto1.CompactTextString(m) }
func (*FuncaRes) ProtoMessage()               {}
func (*FuncaRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FuncaRes) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *FuncaRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FuncaRep struct {
	ID   int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *FuncaRep) Reset()                    { *m = FuncaRep{} }
func (m *FuncaRep) String() string            { return proto1.CompactTextString(m) }
func (*FuncaRep) ProtoMessage()               {}
func (*FuncaRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FuncaRep) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *FuncaRep) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FuncbRes struct {
	Arry []int64 `protobuf:"varint,1,rep,packed,name=arry" json:"arry,omitempty"`
}

func (m *FuncbRes) Reset()                    { *m = FuncbRes{} }
func (m *FuncbRes) String() string            { return proto1.CompactTextString(m) }
func (*FuncbRes) ProtoMessage()               {}
func (*FuncbRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FuncbRes) GetArry() []int64 {
	if m != nil {
		return m.Arry
	}
	return nil
}

type FuncbRep struct {
	Arry []int64 `protobuf:"varint,1,rep,packed,name=arry" json:"arry,omitempty"`
}

func (m *FuncbRep) Reset()                    { *m = FuncbRep{} }
func (m *FuncbRep) String() string            { return proto1.CompactTextString(m) }
func (*FuncbRep) ProtoMessage()               {}
func (*FuncbRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FuncbRep) GetArry() []int64 {
	if m != nil {
		return m.Arry
	}
	return nil
}

func init() {
	proto1.RegisterType((*FuncaRes)(nil), "proto.FuncaRes")
	proto1.RegisterType((*FuncaRep)(nil), "proto.FuncaRep")
	proto1.RegisterType((*FuncbRes)(nil), "proto.FuncbRes")
	proto1.RegisterType((*FuncbRep)(nil), "proto.FuncbRep")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GrpcServer service

type GrpcServerClient interface {
	FuncA(ctx context.Context, in *FuncaRes, opts ...grpc.CallOption) (*FuncaRep, error)
	FuncB(ctx context.Context, in *FuncbRes, opts ...grpc.CallOption) (*FuncbRep, error)
}

type grpcServerClient struct {
	cc *grpc.ClientConn
}

func NewGrpcServerClient(cc *grpc.ClientConn) GrpcServerClient {
	return &grpcServerClient{cc}
}

func (c *grpcServerClient) FuncA(ctx context.Context, in *FuncaRes, opts ...grpc.CallOption) (*FuncaRep, error) {
	out := new(FuncaRep)
	err := grpc.Invoke(ctx, "/proto.GrpcServer/FuncA", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServerClient) FuncB(ctx context.Context, in *FuncbRes, opts ...grpc.CallOption) (*FuncbRep, error) {
	out := new(FuncbRep)
	err := grpc.Invoke(ctx, "/proto.GrpcServer/FuncB", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GrpcServer service

type GrpcServerServer interface {
	FuncA(context.Context, *FuncaRes) (*FuncaRep, error)
	FuncB(context.Context, *FuncbRes) (*FuncbRep, error)
}

func RegisterGrpcServerServer(s *grpc.Server, srv GrpcServerServer) {
	s.RegisterService(&_GrpcServer_serviceDesc, srv)
}

func _GrpcServer_FuncA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuncaRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServerServer).FuncA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcServer/FuncA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServerServer).FuncA(ctx, req.(*FuncaRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcServer_FuncB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuncbRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServerServer).FuncB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcServer/FuncB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServerServer).FuncB(ctx, req.(*FuncbRes))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrpcServer",
	HandlerType: (*GrpcServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FuncA",
			Handler:    _GrpcServer_FuncA_Handler,
		},
		{
			MethodName: "FuncB",
			Handler:    _GrpcServer_FuncB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto1.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9,
	0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9,
	0x79, 0xc5, 0x10, 0x45, 0x4a, 0x7a, 0x5c, 0x1c, 0x6e, 0xa5, 0x79, 0xc9, 0x89, 0x41, 0xa9, 0xc5,
	0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x4c, 0x9e, 0x2e,
	0x42, 0x42, 0x5c, 0x2c, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0x36, 0x92, 0xfa, 0x02, 0xa2, 0xd4, 0xcb, 0x41, 0xd4, 0x27, 0x81, 0xcc, 0x17, 0xe2, 0x62, 0x49,
	0x2c, 0x2a, 0xaa, 0x94, 0x60, 0x54, 0x60, 0xd6, 0x60, 0x0e, 0x02, 0xb3, 0x91, 0xe4, 0x0b, 0xb0,
	0xc9, 0x1b, 0xb5, 0x32, 0x72, 0x71, 0xb9, 0x17, 0x15, 0x24, 0x07, 0xa7, 0x16, 0x95, 0xa5, 0x16,
	0x09, 0x59, 0x72, 0xb1, 0x82, 0x94, 0x3b, 0x0a, 0xf1, 0x43, 0xdc, 0xaf, 0x07, 0x73, 0xbc, 0x14,
	0x9a, 0x40, 0x81, 0x12, 0x5f, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x38, 0x84, 0xd8, 0xf4, 0x21, 0x3a,
	0x6c, 0x20, 0x5a, 0x9d, 0x50, 0xb4, 0x26, 0xa1, 0x6b, 0x05, 0x39, 0x44, 0x49, 0x10, 0xac, 0x95,
	0x5b, 0x09, 0xa2, 0xd5, 0xc9, 0x8a, 0x51, 0x2b, 0x89, 0x0d, 0xac, 0xc4, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xcf, 0xa2, 0xad, 0x69, 0x61, 0x01, 0x00, 0x00,
}
